apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: endringslogg
  namespace: pto
  labels:
    team: pto
spec:
  env:
    - name: CORS_ALLOWED_ORIGINS
      value: 'https://poao-endringslogg.ansatt.dev.nav.no/endringslogg,https://poao-sanity.ansatt.dev.nav.no/systemmeldinger,https://poao-endringslogg.ansatt.dev.nav.no/analytics/session-duration'
    - name: CORS_ALLOWED_METHODS
      value: 'GET,POST,OPTIONS'
    - name: CORS_ALLOWED_HEADERS
      value: 'Referer, Origin, Content-Type, Accept, X-Requested-With, cache-control, x_Nav-CallId, pragma, expires'
  accessPolicy:
    inbound:
      rules:
        - application: veilarbportefoljeflatefs
          namespace: obo
    outbound:
      external:
        - host: li581mqu.api.sanity.io
        - host: cdn.sanity.io
  image: {{image}}
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - name: endringslogg-v3
        type: POSTGRES_14
        tier: db-custom-1-3840
        databases:
          - envVarPrefix: DB
            name: endringslogg
  ingresses:
    - https://poao-endringslogg.intern.dev.nav.no
    - https://poao-endringslogg.ansatt.dev.nav.no
    - https://poao-sanity.intern.dev.nav.no
    - https://poao-sanity.ansatt.dev.nav.no