apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: endringslogg
  namespace: pto
  labels:
    team: pto
spec:
  env:
    - name: CORS_ALLOWED_ORIGINS
      value: 'https://app.adeo.no,https://veilarbportefoljeflatefs.nais.adeo.no,https://veilarbportefoljeflatefs-q1.nais.preprod.local,https://app-q1.adeo.no,https://app-q1.dev.adeo.no,https://veilarbportefoljeflate.intern.dev.nav.no,https://veilarbportefoljeflate.intern.nav.no,https://veilarbportefoljeflate.ansatt.dev.nav.no'
    - name: CORS_ALLOWED_METHODS
      value: 'GET,POST,OPTIONS,PATCH'
    - name: CORS_ALLOWED_HEADERS
      value: 'Content-Type,Authorization,Nav-Consumer-Id'
  accessPolicy:
    inbound:
      rules:
        - application: veilarbportefoljeflatefs
          namespace: obo
    outbound:
      external:
        - host: li581mqu.api.sanity.io
        - host: cdn.sanity.io
  image: {{image}}
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - name: endringslogg-v3
        type: POSTGRES_14
        tier: db-custom-1-3840
        databases:
          - envVarPrefix: DB
            name: endringslogg
  ingresses:
    - https://poao-endringslogg.intern.dev.nav.no
    - https://poao-endringslogg.ansatt.dev.nav.no
    - https://poao-sanity.intern.dev.nav.no
    - https://poao-sanity.ansatt.dev.nav.no
